
version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: vg-postgres
    restart: always
    environment:
      POSTGRES_USER: vgroot
      POSTGRES_PASSWORD: vgroot
      POSTGRES_DB: vgdb
      PGTZ: Asia/Kolkata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./000-init.sql:/docker-entrypoint-initdb.d/000-init.sql

volumes:
  postgres_data:
