spring.application.name=pv-app
spring.datasource.url=jdbc:postgresql://localhost:5432/vgdb
spring.datasource.username=vgroot
spring.datasource.password=vgroot
spring.liquibase.change-log=classpath:db/changelog/db.changelog-migration.xml

spring.liquibase.default-schema=vg-sc1
spring.liquibase.liquibase-schema=vg-sc1
spring.jpa.properties.hibernate.default_schema=vg-sc1
spring.parameters.strict-validation=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
#spring.jpa.properties.hibernate.type.json_format_mapper=jackson