spring.application.name=pv-app
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres-vg
spring.datasource.password=postgres-vg
spring.liquibase.change-log=classpath:db/changelog/db.changelog-migration.xml

spring.liquibase.default-schema=postgres-vg-sc1
spring.liquibase.liquibase-schema=postgres-vg-sc1
spring.jpa.properties.hibernate.default_schema=postgres-vg-sc1
spring.parameters.strict-validation=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata